server {
    listen 80;
    server_name localhost;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
    
    location /saluda {
        proxy_pass http://hola:5000;
    }
}
